version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env